### PR TITLE
Integrate French Translation

### PR DESCRIPTION
**Pull request by 5axes**
Translation integration partially completed 
Files modified for QT6 only
Messages still to be translated

Main menu not translated

### CODE REVIEW

**Comment by 5axes** [comment]
For the parameters list translation, it's a bit more complicated, I've modified the Pyhton files in the Models folder! but the parameter text is sometimes used as a parameter ... It's solved for BedLevel tests, but I'm not sure if other problems are generated by translating parameters

**Comment by 5axes** [comment]
Translate also the menu and perform some test

**Comment by 5axes** [comment]
Extremely strange, I have the impression that a lot of scripts are not applied.  At first I thought it was due to my modifications, but when I tested an official version I got the same results...   Are there any problems in the latest versions on towers a little more exotic than the temp tower?

**Comment by 5axes** [comment]
Tests performed on Cura version 5.0 On Windows 10  ( This is my dev version, where I can modify my plugins without affecting the versions I use )

- Bed Level Pattern
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> N/A
    
- Retraction Tower
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> Not tested
    
- Fan Tower
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> N/A
    
- Speed Tower
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> KO

Error
image


- Flow Tower
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> KO
    
- [Temp Tower]
    - Standard Model Creation -> Ok for All
    - Custom Model Creation -> Ok
    - Postprocess Code Generation -> OK

**Review by 5axes — COMMENTED** [review]
same issue

**Comment by 5axes** [comment]
Traduction de divers petit message dans le programme principale.

Files modified for QT6 only

Parameters and Test name  translated
Messages translated
Main menu translated

**Review by 5axes — COMMENTED** [review]
ok

**Comment by kartchnb** [comment]
@5axes, I am constantly impressed by you.  I've been meaning to look into what is required for translation, but haven't got around to it.  Thank you for working on this.

I'll check into why the scripts are not being applied.  I'm currently in the middle of making some more changes and may have got things into a bad state.  I've been putting off some testing, but should probably get into that now.

**Comment by kartchnb** [comment]
My recent changes introduced the errors you found and broke how preset tower settings are applied.  Both should be fixed and I've done a great deal of testing tonight to make sure.

I'll work on merging your pull request now.

**Review by kartchnb — APPROVED** [review]

**Pull request merged**
